using Pkg
Pkg.add("AMQPClient")
Pkg.add("Distributions")
Pkg.add("Formatting")
Pkg.add("ForwardDiff")
Pkg.add("FreudenthalTriangulations")
Pkg.add("GLPK")
Pkg.add("Ipopt")
Pkg.add("Ipopt")
Pkg.add("IterTools")
Pkg.add("IterTools")
Pkg.add("JuMP")
Pkg.add("LightGraphs")
Pkg.add("LinearAlgebra")
Pkg.add("SpecialFunctions")
Pkg.add("SafeTestsets")
