
function prior(vars, G)
    """
    A function for generating a prior αijk where all entries are 1. 
    The array of matrices that this function returns 
    takes the same form as the statistics generated by algorithm 4.1. 
    To determine the appropriate dimensions, 
    the function takes as input the list of variables vars and structure G.
    """
    n = length(vars)
    r = [vars[i].r for i = 1:n]
    q = [prod([r[j] for j in inneighbors(G, i)]) for i = 1:n]
    return [ones(q[i], r[i]) for i = 1:n]
end
