using LightGraphs
using Test
using DecisionMakingAlgorithms

@testset "test prior " begin
    #generating a prior αijk where all entries are 1. 
    #The array of matrices that this function returns 
    #takes the same form as the statistics generated by algorithm 4.1. 
    #To determine the appropriate dimensions, 
    #the function takes as input the list of variables vars and structure G.
    G = SimpleDiGraph(3)
    add_edge!(G, 1, 2)
    add_edge!(G, 3, 2)
    vars = [Variable(:A, 2), Variable(:B, 2), Variable(:C, 2)]
    result = prior(vars, G)
    @test result == [[1.0 1.0], [1.0 1.0; 1.0 1.0; 1.0 1.0; 1.0 1.0], [1.0 1.0]]
end
